name: aspnet-core-ci

on:
  pull_request:
    paths:
    - .github/workflows/aspnet-core-**
    - libs/aspnet-core**
  push:
    branches:
    - main
    paths:
    - .github/workflows/aspnet-core-**
    - libs/aspnet-core**
    tags:
    - "aspnet-core-*"

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      FEEDZ_LOGICALITY_API_KEY: ${{secrets.FEEDZ_LOGICALITY_API_KEY}}

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Find PR Number
      uses: jwalton/gh-find-current-pr@v1
      
    - run: echo "Your PR is ${PR}"
      if: success() && steps.findPr.outputs.number
      env:
          PR: ${{ steps.findPr.outputs.pr }}
    
    - name: Print Environment
      run: printenv
      shell: bash

    - name: Test
      run: bash build.sh aspnet-core-test
      shell: bash

    - name: Pack
      run: bash build.sh aspnet-core-pack
      shell: bash

    - name: Push
      if: github.event_name == 'push'
      run: bash build.sh push
      shell: bash

    - uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: artifacts
