name: CI

on:
  push:
    branches:
    - main
    tags:
    - v*

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      FEEDZ_LOGICALITY_API_KEY: ${{secrets.FEEDZ_LOGICALITY_API_KEY}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build and Test
      run: bash build.sh
      shell: bash
